" -----------------------------------------
" Vundle
" https://github.com/gmarik/Vundle.vim
" -----------------------------------------

set nocompatible
set backspace=2
set cc=95
set laststatus=2
set ruler
set statusline="%f%p"
filetype off

" set the runtime path to include Vundle and initialize

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
" call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" Install YCM
Plugin 'Valloric/YouCompleteMe'

" Dracula Theme
Plugin 'dracula/vim', { 'name': 'dracula' }

Plugin 'scrooloose/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'

" all of your plugins must be added before the following line
call vundle#end()
filetype plugin indent on

" Brief help
" :PluginList            - lists configured plugins
" :PluginInstall         - installs plugins; append '!' to update;
" :PluginUpdate          - update plugins
" :PluginSearch foo      - searches for foo; append '!' to refresh local cache
" :PluginClean           - confirms removal of unused plugins

syntax on
set hlsearch
set incsearch
set nu!
set ignorecase
set laststatus=2
set completeopt-=preview
set listchars=eol:<,tab:>-,trail:~,extends:^,precedes:>
set list
set cul
set cuc
set guifont=JetBrains\ Mono:h17
set autoindent
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2

let Tlist_Show_One_File=1
let Tlist_Exit_OnlyWindow=1   " 如果taglist 窗口是最后一个窗口则关闭 vim
let Tlist_Ctags_Cmd="`brew --prefix`/bin/ctags"

let g:ycm_global_ycm_extra_conf="~/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py"

colorscheme molokai
set csre
